name: protoc-gen-go-genkit-tools

on:
  push:
    branches: ["**"]
    tags: ["v*"]
  pull_request:
    paths:
      - "**"
      - ".github/workflows/build.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install buf CLI
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Go test
        run: go test ./...
      - name: Buf lint
        run: buf lint
      - name: Buf generate (sanity)
        run: buf generate

  push-bsr:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Install buf CLI
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Buf push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: buf push
